import './runner.css';

interface BreachOptions { onExit(collection?: boolean): void; onWin(collectibles: string[]): string; reducedMotion(): boolean; setReducedMotion(value: boolean): void }
type Screen = 'ready' | 'playing' | 'paused' | 'won' | 'lost';

/** Track 04 microgame: compact top-down breach arena reusing the lightweight Canvas contract. */
export function mountBreach(host: HTMLElement, options: BreachOptions) {
  host.innerHTML = `<div class="runner-game breach-game" data-screen="ready"><canvas data-breach-canvas aria-label="Arena de Rumildo"></canvas><div class="runner-noise" aria-hidden="true"></div><header class="runner-hud"><span>PSICOZ / TRACK_04</span><strong data-breach-score>HOSTIS 00 / 10</strong><span data-breach-time>00:30</span></header><p class="runner-objective" data-breach-objective>Rompa dez entidades antes do bloqueio fechar.</p><p class="runner-notice" data-breach-notice role="status"></p><section class="runner-overlay"><div class="runner-card"><p class="section-label">psicoZ / microexperiência</p><h2>Rumildo</h2><strong>BREACH // HOSTILE MEMORY</strong><p>Entre na arena, mire com o mouse ou toque e interrompa dez entidades. WASD e setas movimentam.</p><p class="runner-controls">Clique, toque ou Espaço dispara. P pausa.</p><div class="runner-result" hidden><strong data-breach-result>TRACK RECOVERED</strong><p data-breach-save></p></div><div class="runner-actions"><button type="button" class="button primary" data-breach-start>Invadir o arquivo</button><button type="button" class="button secondary" data-breach-restart hidden>Recomeçar</button><button type="button" class="text-link" data-breach-exit>Voltar à home</button></div></div></section></div>`;
  const root = host.querySelector<HTMLElement>('.breach-game')!; const canvas = root.querySelector<HTMLCanvasElement>('[data-breach-canvas]')!; const ctx = canvas.getContext('2d')!; const overlay = root.querySelector<HTMLElement>('.runner-overlay')!; const abort = new AbortController();
  let screen: Screen = 'ready'; let frame = 0; let last = 0; let elapsed = 0; let score = 0; let x = .5; let y = .55; let aimX = .5; let aimY = .5; let enemies: Array<{x:number;y:number;speed:number}> = []; let shots: Array<{x:number;y:number;vx:number;vy:number}> = []; let keys = new Set<string>(); let disposed = false;
  const notice = (text:string) => { root.querySelector<HTMLElement>('[data-breach-notice]')!.textContent = text; };
  const resize = () => { const ratio = Math.min(2, devicePixelRatio || 1); const rect = canvas.getBoundingClientRect(); canvas.width = Math.round(rect.width * ratio); canvas.height = Math.round(rect.height * ratio); ctx.setTransform(ratio,0,0,ratio,0,0); };
  const draw = () => { const w=canvas.clientWidth,h=canvas.clientHeight; ctx.fillStyle='#090707';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#401923'; for(let i=1;i<8;i++){ctx.beginPath();ctx.moveTo(w*i/8,0);ctx.lineTo(w*i/8,h);ctx.moveTo(0,h*i/8);ctx.lineTo(w,h*i/8);ctx.stroke();} ctx.fillStyle='#ef233c'; enemies.forEach(e=>{ctx.beginPath();ctx.arc(e.x*w,e.y*h,12,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f4eee8';ctx.stroke();}); ctx.fillStyle='#f4eee8';ctx.fillRect(x*w-10,y*h-10,20,20); ctx.fillStyle='#ff4054';shots.forEach(s=>{ctx.fillRect(s.x*w-3,s.y*h-3,6,6);}); };
  const updateHud=()=>{root.querySelector<HTMLElement>('[data-breach-score]')!.textContent=`HOSTIS ${String(score).padStart(2,'0')} / 10`;root.querySelector<HTMLElement>('[data-breach-time]')!.textContent=`00:${String(Math.max(0,30-Math.ceil(elapsed))).padStart(2,'0')}`;root.querySelector<HTMLElement>('[data-breach-objective]')!.textContent=score>=10?'Núcleo aberto. Arquivo recuperado.':`Interrompa ${10-score} entidades antes do bloqueio fechar.`;};
  const show=(next:Screen)=>{screen=next;root.dataset.screen=next;overlay.hidden=next==='playing';root.querySelector<HTMLElement>('.runner-result')!.hidden=next!=='won';root.querySelector<HTMLButtonElement>('[data-breach-start]')!.hidden=!(next==='ready'||next==='paused');root.querySelector<HTMLButtonElement>('[data-breach-restart]')!.hidden=!(next==='won'||next==='lost');if(next!=='playing')cancelAnimationFrame(frame);if(next==='won'){root.querySelector<HTMLElement>('[data-breach-save]')!.textContent=options.onWin(['rumildo-core']);}updateHud();};
  const reset=()=>{elapsed=0;score=0;x=.5;y=.55;aimX=.5;aimY=.5;enemies=[];shots=[];show('ready');draw();};
  const fire=()=>{if(screen!=='playing')return;const dx=aimX-x,dy=aimY-y,len=Math.hypot(dx,dy)||1;shots.push({x,y,vx:dx/len*.95,vy:dy/len*.95});};
  const tick=(time:number)=>{if(disposed||screen!=='playing')return;const dt=Math.min(.05,Math.max(0,(time-last)/1000));last=time;elapsed+=dt;const speed=dt*.42;if(keys.has('KeyA')||keys.has('ArrowLeft'))x-=speed;if(keys.has('KeyD')||keys.has('ArrowRight'))x+=speed;if(keys.has('KeyW')||keys.has('ArrowUp'))y-=speed;if(keys.has('KeyS')||keys.has('ArrowDown'))y+=speed;x=Math.max(.05,Math.min(.95,x));y=Math.max(.08,Math.min(.92,y));if(enemies.length<4&&Math.random()<dt*.9)enemies.push({x:Math.random()*.9+.05,y:Math.random()*.75+.1,speed:.035+Math.random()*.025});enemies.forEach(e=>{const dx=x-e.x,dy=y-e.y,l=Math.hypot(dx,dy)||1;e.x+=dx/l*e.speed*dt;e.y+=dy/l*e.speed*dt;});shots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;});for(let i=shots.length-1;i>=0;i--){let hit=-1;for(let j=0;j<enemies.length;j++)if(Math.hypot(shots[i].x-enemies[j].x,shots[i].y-enemies[j].y)<.055){hit=j;break;}if(hit>=0){enemies.splice(hit,1);shots.splice(i,1);score++;if(score>=10){show('won');return;}}else if(shots[i].x<0||shots[i].x>1||shots[i].y<0||shots[i].y>1)shots.splice(i,1);}if(enemies.some(e=>Math.hypot(x-e.x,y-e.y)<.045)||elapsed>=30){notice('BREACH NEGADO — reabra o arquivo');show('lost');return;}updateHud();draw();frame=requestAnimationFrame(tick);};
  const start=()=>{if(screen==='won'||screen==='lost')reset();show('playing');last=performance.now();frame=requestAnimationFrame(tick);};
  root.querySelector('[data-breach-start]')!.addEventListener('click',start,{signal:abort.signal});root.querySelector('[data-breach-restart]')!.addEventListener('click',reset,{signal:abort.signal});root.querySelector('[data-breach-exit]')!.addEventListener('click',()=>options.onExit(),{signal:abort.signal});canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();aimX=(e.clientX-r.left)/r.width;aimY=(e.clientY-r.top)/r.height;},{signal:abort.signal});canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect();aimX=(e.clientX-r.left)/r.width;aimY=(e.clientY-r.top)/r.height;fire();},{signal:abort.signal});window.addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space'){e.preventDefault();fire();}if(e.code==='KeyP'||e.code==='Escape')show(screen==='playing'?'paused':screen==='paused'?'playing':screen);},{signal:abort.signal});window.addEventListener('keyup',e=>keys.delete(e.code),{signal:abort.signal});window.addEventListener('resize',()=>{resize();draw();},{signal:abort.signal});resize();draw();show('ready');
  return {pause:()=>{if(screen==='playing')show('paused');},dispose:()=>{disposed=true;cancelAnimationFrame(frame);abort.abort();host.replaceChildren();}};
}
