import './runner.css';
interface ZeroOptions { onExit(collection?: boolean): void; onWin(collectibles: string[]): string; reducedMotion(): boolean; setReducedMotion(value: boolean): void }
type Screen = 'ready' | 'playing' | 'paused' | 'won' | 'lost';
type Platform = { x: number; y: number; w: number };
/** Track 05: a small platformer with actual landing, jump and dash rules. */
export function mountZero(host: HTMLElement, options: ZeroOptions) {
  host.innerHTML = `<div class="runner-game zero-game" data-screen="ready"><canvas data-zero-canvas aria-label="Platformer de Inverso"></canvas><div class="runner-noise" aria-hidden="true"></div><header class="runner-hud"><span>PSICOZ / TRACK_05</span><strong data-zero-score>FRAGMENTOS 0 / 8</strong><span data-zero-time>00:45</span></header><p class="runner-objective" data-zero-objective>Alcance o núcleo invertido.</p><p class="runner-notice" data-zero-notice role="status"></p><section class="runner-overlay"><div class="runner-card"><p class="section-label">psicoZ / microexperiência</p><h2>Inverso</h2><strong>ZERO // PLATFORM BREAK</strong><p>Salte entre as plataformas e atravesse a falha. Espaço pula; Shift faz um dash curto.</p><div class="runner-result" hidden><strong>TRACK RECOVERED</strong><p data-zero-save></p></div><div class="runner-actions"><button type="button" class="button primary" data-zero-start>Entrar no loop</button><button type="button" class="button secondary" data-zero-restart hidden>Recomeçar</button><button type="button" class="text-link" data-zero-exit>Voltar à home</button></div></div></section></div>`;
  const root = host.querySelector<HTMLElement>('.zero-game')!; const canvas = root.querySelector<HTMLCanvasElement>('[data-zero-canvas]')!; const ctx = canvas.getContext('2d')!; const overlay = root.querySelector<HTMLElement>('.runner-overlay')!; const abort = new AbortController();
  const platforms: Platform[] = [{ x: .02, y: .82, w: .26 }, { x: .33, y: .67, w: .2 }, { x: .59, y: .52, w: .19 }, { x: .8, y: .72, w: .18 }, { x: .44, y: .88, w: .23 }];
  let screen: Screen = 'ready'; let frame = 0; let last = 0; let elapsed = 0; let score = 0; let x = .08; let y = .785; let vy = 0; let dash = 0; let grounded = true; let lastPlatform = 0; let keys = new Set<string>(); let disposed = false;
  const notice = (message: string) => { root.querySelector<HTMLElement>('[data-zero-notice]')!.textContent = message; };
  const resize = () => { const ratio = Math.min(2, devicePixelRatio || 1); const bounds = canvas.getBoundingClientRect(); canvas.width = Math.round(bounds.width * ratio); canvas.height = Math.round(bounds.height * ratio); ctx.setTransform(ratio, 0, 0, ratio, 0, 0); };
  const draw = () => { const w = canvas.clientWidth; const h = canvas.clientHeight; ctx.fillStyle = '#090707'; ctx.fillRect(0, 0, w, h); ctx.strokeStyle = '#451722'; for (let i = 0; i < 9; i++) { ctx.beginPath(); ctx.moveTo(0, i * h / 9); ctx.lineTo(w, i * h / 9); ctx.stroke(); } ctx.fillStyle = '#9d1429'; platforms.forEach((platform) => ctx.fillRect(platform.x * w, platform.y * h, platform.w * w, 10)); ctx.fillStyle = '#f4eee8'; ctx.fillRect(x * w - 12, y * h - 30, 24, 30); ctx.fillStyle = '#ef233c'; for (let i = 0; i < score; i++) ctx.fillRect((.2 + i * .075) * w, (.25 + Math.sin(elapsed + i) * .03) * h, 8, 8); };
  const updateHud = () => { root.querySelector<HTMLElement>('[data-zero-score]')!.textContent = `FRAGMENTOS ${score} / 8`; root.querySelector<HTMLElement>('[data-zero-time]')!.textContent = `00:${String(Math.max(0, 45 - Math.ceil(elapsed))).padStart(2, '0')}`; root.querySelector<HTMLElement>('[data-zero-objective]')!.textContent = score >= 8 ? 'Núcleo alcançado.' : `Alcance as plataformas e recupere ${8 - score} fragmentos.`; };
  const show = (next: Screen) => { screen = next; root.dataset.screen = next; overlay.hidden = next === 'playing'; root.querySelector<HTMLElement>('.runner-result')!.hidden = next !== 'won'; root.querySelector<HTMLButtonElement>('[data-zero-start]')!.hidden = !(next === 'ready' || next === 'paused'); root.querySelector<HTMLButtonElement>('[data-zero-restart]')!.hidden = !(next === 'lost' || next === 'won'); if (next !== 'playing') cancelAnimationFrame(frame); if (next === 'won') root.querySelector<HTMLElement>('[data-zero-save]')!.textContent = options.onWin(['inverso-core']); updateHud(); };
  const reset = () => { elapsed = 0; score = 0; x = .08; y = .785; vy = 0; dash = 0; grounded = true; lastPlatform = 0; show('ready'); draw(); };
  const jump = () => { if (screen === 'playing' && grounded) { vy = -.88; grounded = false; } };
  const tick = (time: number) => { if (disposed || screen !== 'playing') return; const dt = Math.min(.05, Math.max(0, (time - last) / 1000)); last = time; elapsed += dt; let direction = 0; if (keys.has('ArrowRight') || keys.has('KeyD')) direction += 1; if (keys.has('ArrowLeft') || keys.has('KeyA')) direction -= 1; if (keys.has('ShiftLeft') || keys.has('ShiftRight')) dash = Math.max(dash, .16); x += direction * dt * (dash > 0 ? 1.7 : .72); dash = Math.max(0, dash - dt); vy += 2.1 * dt; const previousY = y; y += vy * dt; grounded = false; for (const platform of platforms) if (vy >= 0 && previousY <= platform.y - .035 && y >= platform.y - .035 && x + .025 >= platform.x && x - .025 <= platform.x + platform.w) { y = platform.y - .035; vy = 0; grounded = true; break; } if (x > .97) { x = .08; score = Math.min(8, score + 1); notice(`Fragmento ${score}/8 recuperado`); } if (y > 1.05) { notice('QUEDA SEM PLATAFORMA — reinicie o loop'); show('lost'); return; } if (score >= 8) { show('won'); return; } if (elapsed >= 45) { show('lost'); return; } updateHud(); draw(); frame = requestAnimationFrame(tick); };
  const start = () => { if (screen === 'won' || screen === 'lost') reset(); show('playing'); last = performance.now(); frame = requestAnimationFrame(tick); };
  root.querySelector('[data-zero-start]')!.addEventListener('click', start, { signal: abort.signal }); root.querySelector('[data-zero-restart]')!.addEventListener('click', reset, { signal: abort.signal }); root.querySelector('[data-zero-exit]')!.addEventListener('click', () => options.onExit(), { signal: abort.signal }); canvas.addEventListener('pointerdown', jump, { signal: abort.signal }); window.addEventListener('keydown', (event) => { keys.add(event.code); if (event.code === 'Space' || event.code === 'ArrowUp') { event.preventDefault(); jump(); } if (event.code === 'Escape') show(screen === 'playing' ? 'paused' : screen === 'paused' ? 'playing' : screen); }, { signal: abort.signal }); window.addEventListener('keyup', (event) => keys.delete(event.code), { signal: abort.signal }); window.addEventListener('resize', () => { resize(); draw(); }, { signal: abort.signal }); resize(); draw(); show('ready');
  return { pause: () => { if (screen === 'playing') show('paused'); }, dispose: () => { disposed = true; cancelAnimationFrame(frame); abort.abort(); host.replaceChildren(); } };
}

